Hello, I am trying to display some statistics for OIS and SOFR rates in ths section.

In [ ]:
import numpy as np
import pandas as pd

In [5]:

A = np.random.randn(5,5)

print A

[[-1.85082305  0.07971733  0.64729173  1.18430621 -0.13561641]
 [ 1.77830281  0.61908793  0.3817487   1.12847838 -1.16638173]
 [ 0.52822434 -1.19053342  1.0047015  -0.40164692 -0.85443783]
 [-0.55876506  0.2331296  -1.15853137 -1.13460206 -0.27620831]
 [-1.72787116 -1.63703718  1.20467635  0.37045518 -0.74128934]]


In [ ]:
THen I am going to save this now....
